"""message

Revision ID: 28a9366bf6a5
Revises: ef90f6bae915
Create Date: 2024-07-08 01:44:36.385686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a9366bf6a5'
down_revision = 'ef90f6bae915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
